FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install torch --index-url https://download.pytorch.org/whl/cpu

RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

COPY . .

RUN mkdir -p uploads chroma_db

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
